In [3]:
import pandas as pd
import numpy as np
ser = pd.Series(np.random.randint(1,10,35))

In [4]:
'''Mã lệnh trên có ý nghĩa là:
np.random.randint(1,10,35) trả về 1 mảng số nguyên ngẫu nhiên có giá trị min là 1, giá trị max là 10 với kích cỡ 35 phần tử
sau đó ta dùng pd.Series để tạo 1 chuỗi pandas từ mảng số ngẫu nhiên ở trên
'''

'Mã lệnh trên có ý nghĩa là:\nnp.random.randint(1,10,35) trả về 1 mảng số nguyên ngẫu nhiên có giá trị min là 1, giá trị max là 10 với kích cỡ 35 phần tử\nsau đó ta dùng pd.Series để tạo 1 chuỗi pandas từ mảng số ngẫu nhiên ở trên\n'

In [5]:
arr = ser.values  # chuyển đối tượng series thành array
new_ser = arr.reshape((7,5))
print(new_ser, "\nđã định hình có 7 hàng 5 cột")

[[3 4 7 5 7]
 [4 6 1 5 8]
 [2 1 9 6 7]
 [9 6 1 2 1]
 [6 9 8 4 1]
 [4 2 2 3 3]
 [9 1 8 1 7]] 
đã định hình có 7 hàng 5 cột
