In [1]:
# khởi tạo array có giá trị từ 0-9
import numpy as np
arr = np.arange(10)

# hiển thị các phần tử trong array
print(arr)

# xem kiểu dữ liệu
print(arr.dtype)

# kích thước
print(arr.shape)

arr_even = arr[0:10:2]
print(arr_even, "là array gồm phần tử chẵn")
arr_odd = arr[1:10:2]
print(arr_odd, "là array gồm phần tử lẻ")

arr[1:10:2] = 100
arr_update_1 = arr
print(arr_update_1, "là array được cập nhật từ array ban đầu")

[0 1 2 3 4 5 6 7 8 9]
int64
(10,)
[0 2 4 6 8] là array gồm phần tử chẵn
[1 3 5 7 9] là array gồm phần tử lẻ
[  0 100   2 100   4 100   6 100   8 100] là array được cập nhật từ array ban đầu
