In [1]:
import numpy as np
arr_zeros = np.zeros(10,dtype=int)
arr_zeros[5] = 1
print(arr_zeros, "là array đã cập nhật phần tử vị trí thứ 5 từ arr_zeros")

arr_h = np.arange(10,25)
print(arr_h[::-1], "là array đảo ngược của arr_h")

arr_k = np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_l = arr_k[(arr_k !=0)]
print(arr_l, "là array với các phần tử của arr_k khác 0")

arr_l = np.concatenate((arr_l[:7], [10], [20], arr_l[8:]))
print(arr_l, "là array_l với phần tử mới được thêm vào cuối array")

arr_l[5] = 100
print(arr_l, "là array_l với phần tử vị trí 5 có giá trị 100")

arr_l = np.delete(arr_l, [0,3])
print(arr_l, "là array_l đã xóa các phần tử vị trí 0,1,2")

[0 0 0 0 0 1 0 0 0 0] là array đã cập nhật phần tử vị trí thứ 5 từ arr_zeros
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10] là array đảo ngược của arr_h
[1 2 8 2 1 3 5] là array với các phần tử của arr_k khác 0
[ 1  2  8  2  1  3  5 10 20] là array_l với phần tử mới được thêm vào cuối array
[  1   2   8   2   1 100   5  10  20] là array_l với phần tử vị trí 5 có giá trị 100
[  2   8   1 100   5  10  20] là array_l đã xóa các phần tử vị trí 0,1,2
