In [1]:
#1
import numpy as np
arr = np.array([[True,True,True],
               [True,True,True],
               [True,True,True]])

#2
arr_1D = np.array([0,1,2,3,4,5,6,7,8])
arr_2D = np.reshape(arr_1D, (3,3))
print(arr_2D, "là định dạng 3x3 cho arr_1D")
hoan_doi = arr_2D[:,2].copy()
arr_2D[:,2] = arr_2D[:,0]
arr_2D[:,0] = hoan_doi
print(arr_2D, "là định dạng chuyển cột 1 sang cột 3 và ngược lại")

#3
hoan_doi_2 = arr_2D[0,:].copy()
arr_2D[0,:] = arr_2D[1,:]
arr_2D[1,:] = hoan_doi_2
print(arr_2D, "là định dạng chuyển dòng 1 sang dòng 2 và ngược lại")

#4
arr_2D = np.flip(arr_2D, axis=1)
print(arr_2D, "là arr 2D đã đảo ngược các dòng")

#5
arr_2D = np.flip(arr_2D, axis=0)
print(arr_2D, "là arr 2D đã đảo ngược theo cột")

#6
arr_2D_null = np.array([[1,2,3],[np.nan,5,6],[7,np.nan,9],[4,5,6]])
np.isnan(arr_2D_null)    # trả về true nếu có giá trị rỗng 

#7
arr_2D_null[np.isnan(arr_2D_null)] = 0
print(arr_2D_null, "là arr 2D null với các giá trị rỗng thay = số 0")

[[0 1 2]
 [3 4 5]
 [6 7 8]] là định dạng 3x3 cho arr_1D
[[2 1 0]
 [5 4 3]
 [8 7 6]] là định dạng chuyển cột 1 sang cột 3 và ngược lại
[[5 4 3]
 [2 1 0]
 [8 7 6]] là định dạng chuyển dòng 1 sang dòng 2 và ngược lại
[[3 4 5]
 [0 1 2]
 [6 7 8]] là arr 2D đã đảo ngược các dòng
[[6 7 8]
 [0 1 2]
 [3 4 5]] là arr 2D đã đảo ngược theo cột
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]] là arr 2D null với các giá trị rỗng thay = số 0
